
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Prisma Client generation doesn't need a live DB connection.
    // Default to a local Postgres URL if DATABASE_URL isn't set (dev convenience).
    // NOTE: On Vercel you MUST set DATABASE_URL to a persistent Postgres DB.
    url: process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432/tc_simple?schema=public",
  },
});
