
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Vercel builds can run `prisma generate` before env vars are configured.
    // Prisma Client generation doesn't need a live DB connection, but Prisma's `env()`
    // helper throws if the variable is missing. Provide a safe SQLite fallback.
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
