// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function isPostgresUrl(url: string | undefined | null): url is string {
  return typeof url === "string" && /^(postgresql|postgres):\/\//.test(url);
}

function pickDatabaseUrl(): string {
  // Prefer platform-provided Postgres URLs (Vercel Postgres / Neon / etc).
  const candidates = [
    process.env.POSTGRES_PRISMA_URL,
    process.env.POSTGRES_URL_NON_POOLING,
    process.env.POSTGRES_URL,
    process.env.DATABASE_URL,
  ];

  const picked = candidates.find(isPostgresUrl);
  return picked ?? "postgresql://postgres:postgres@localhost:5432/tc_simple?schema=public";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Prisma Client generation doesn't need a live DB connection, but it DOES validate the URL.
    // If DATABASE_URL is missing/invalid on Vercel, fall back to POSTGRES_* vars when available.
    url: pickDatabaseUrl(),
  },
});
